### ISSUE TITLE
Implement rate limits

### ISSUE THREAD

**Issue by jgrim** [sublinks/sublinks-api#116]

**Comment by Pdzly** [comment]
Implement rate limit per IP

( If possible per user,  in the future probably another ratelimit IF they are logged in. )

**Comment by jgrim** [comment]
Rate limit by IP if not authorized. Then by user if authorized.

**Comment by devanbenz** [comment]
What mechanism for rate-limiting are we thinking? Something in-memory or maybe TTL indexed DB table inserts? In the past I have used a mix of http middleware and redis with TTL puts to do rate-limiting. IDK how to do middleware in Java so might be a good learning opportunity 😆 I'd be happy to pick this ticket up!

**Comment by jgrim** [comment]
I'd love to do in memory or redis.

**Comment by devanbenz** [comment]
@jgrim l'd opt to use redis because you can define TTLs on inserts with EXPIRE making doing something like token bucket incredibly easy. (https://redis.io/commands/ttl/). Whereas with in-memory we would need to hold state on when to expire the rate-limit and could add some complexity. Please let me know what you think?

**Comment by Pdzly** [comment]
Yeah redis could improve the scallability and to cluster the application. Otherwise in cache it could lead to unwanted side effects.

For the start you just need to implement the lemmy rate limits. 

One thing i would really love, that it could be opt out and that it uses memory for it ( For smaller instances ) But if not possible then i  would say keep it with redis.

**Comment by devanbenz** [comment]
Ah yeah - I started some work on implementing it with Redis: https://github.com/sublinks/sublinks-api/pull/193 @Pdzly feel free to make any comments on this but right now its a draft. I need to look into where Lemmy does rate-limiting but I've set it up in a way where I can easily opt out for certain controller paths.
