### ISSUE TITLE
Limit the ammount of active reports a comment/post could have

### ISSUE THREAD

**Issue by Pdzly** [sublinks/sublinks-api#334]
As a admin i want to limit the maximum of reports a post, comment can have.

If that limit is reached, the reports are getting blocked. Federated reports will be let through.

Idea behind it, that a "unpopular" opinion gets reported by the hundreds and mods have to click through all reports.

**Comment by Pdzly** [comment]
This could be probably outdone by #187  as a "Resolve all by Post" could resolve this issue.

**Comment by gaviscapes** [comment]
Perhaps it could just add onto the existing report instead of duplicating them? Kind of like "this post has been reported this many times" display.

**Comment by jgrim** [comment]
> Perhaps it could just add onto the existing report instead of duplicating them? Kind of like "this post has been reported this many times" display. Or potentially a tag highlighting potential report spamming.

This was what I was going to suggest. We should merge requests into one large report with a counter rather than a bunch of separate ones that need attention.

I don't think limiting reports is a good idea, could break the attention needed to alert mods to an issue. I think it'd be unexpected for a user to create a report that gets rejected because there are too many reports already.

**Comment by Pdzly** [comment]
Ok yeah than this issue is not good for it. 

Here is a successor [#355](https://github.com/sublinks/sublinks-api/issues/355)
